### ISSUE TITLE
IncludeFileContent doesn't seem to work

### ISSUE THREAD

**Issue by Nimzr** [thekevinholman/FragmentLibrary#2]
I ran across this today and will do some further testing to confirm but it looks like $IncludeFileContent/PathoftheScriptInTheProject/Scriptname.ps1$</ScriptBody> doesn't seem to work. I get powershell exception alerts on hosts when a script is referenced this way. But including the full script in the XML seems to work just fine. 

I'll see if I can do further testing to gather more data but I believe it was error 22406 referencing "you must provide a value expression following the '/' operator.

**Comment by thekevinholman** [comment]
I dont use that in any of my fragments.  So are you saying you just cannot get it to work in a fragment you are trying to create?

**Comment by Nimzr** [comment]
Yup sorry 😃 should have been more clear. Replacing a script block in a powershell script fragment with a IncludeFileContent tag seems to cause issues.

**Comment by thekevinholman** [comment]
Gotchya - yeah I tend not to use IncludeFileContent.  It might not work well with fragments.  I don't think anyone used them before VSAE came along, and my customers don't use VSAE - they use Silect MP Author Pro/Studio.

**Comment by Nimzr** [comment]
got it, Want me to close the issue? when I get more time I can try to see what configurations end up working and let you know. Speaking of which.  Do you allow pull requests?

**Comment by Nimzr** [comment]
Hey @thekevinholman This issue is fixed if the script file starts and ends with an empty line. (edit: I should clarify that this is required if the script itself was ending and starting with a comment line, so adding a line before my first comment line and after my last comment line in the script fixed the issue)  I know you said your clients don't use vsae but for those that do this may help keep the mp fragments a bit cleaner and easier to manage.  let me know if you'd like me to close this or if you want to address that somehow since its out of the scope of the fragments you built. Thanks for all your work btw!
