### ISSUE TITLE
Rules generate duplicate alerts for each service discovered on a given server

### ISSUE THREAD

**Issue by ezcodify** [thekevinholman/FragmentLibrary#4]
https://github.com/thekevinholman/FragmentLibrary/blob/1c2ea6c53cafcec5e9085ce971c0436c4efac234/Combo.Class.Discovery.ServiceMonitor.Wildcard.WMIQuery.PSRecovery.mpx#L336

If multiple services are discovered (with wildcard) on an individual server, and let's say the recovery runs and fails, the failed recovery rule (linked above) generates an alert for each service discovered, not just the particular service with the issue.  Is this a targeting issue with the rule? If so how to target to host vs custom service class?

**Comment by thekevinholman** [comment]
You are 100% correct.  I updated this and fixed in 2022.09.14.  I also added a Service Display Name by request to the class discovery, and all alerts.

**Comment by ezcodify** [comment]
> You are 100% correct. I updated this and fixed in 2022.09.14. I also added a Service Display Name by request to the class discovery, and all alerts.

Awesome - thank you!
