### ISSUE TITLE
Status codes / error codes in Monitor.PortCheck.mpx

### ISSUE THREAD

**Issue by PowerProp** [thekevinholman/FragmentLibrary#9]
Hi.

Not really an issue, just for some clarification.
In the fragment Monitor.PortCheck.mpx, the following codes are mentioned, all resulting in error:
          
2147952460
2147952461
2147953401
2147952465

Could the different error codes be explained, or do they all mean the same thing? 

Thanks in advance.

**Comment by thekevinholman** [comment]
These are documented here for the module:
https://learn.microsoft.com/en-us/previous-versions/system-center/developer/jj130214(v=msdn.10)

0 | Success
2147952460 | Connection timed out
2147952461 | Connection refused
2147952465 | Unreachable
2147953401 | DNS resolution failure
